### ISSUE TITLE
Version check failed.  (2.2.3)

### ISSUE THREAD

**Issue by LinesinRows** [lassir/bcrypt-samp#11]
plugin.bcrypt: Version check failed.  
 (Version 2.2.3)
How can i fix it? This error on the server cmd. (Btw, bcrypt working correctly.)

**Comment by lassir** [comment]
The server used for version checks is no longer maintained. You can fix the warning by updating the `bcrypt.inc` to the latest version in `master` branch, which no longer includes the version check: https://github.com/lassir/bcrypt-samp/blob/master/pawn/bcrypt.inc
