### ISSUE TITLE
Problem with rsaenh.dll (Windows 8.1)

### ISSUE THREAD

**Issue by alxndrr** [lassir/bcrypt-samp#5]
![18-10-2015 14-26-01](https://cloud.githubusercontent.com/assets/13527447/10563871/134ff8fc-75a5-11e5-936d-9c03a492d5e9.jpg)
The procedure entry point BCryptDuplicateKey not found in the library of C: \ Windows \ system32 \ rsaenh.dll

**Comment by lassir** [comment]
What's the name of the dll file for bcrypt in your plugins folder?

**Comment by alxndrr** [comment]
bcrypt.dll

**Comment by lassir** [comment]
Try renaming it to bcrypt-samp.dll for instance. Calling it bcrypt.dll seems to conflict with some system dll.

**Comment by alxndrr** [comment]
That helped, thx.
