### ISSUE TITLE
bcrypt v2.2.2 works but the latest doesn't

### ISSUE THREAD

**Issue by ghost** [lassir/bcrypt-samp#9]
Well on Linux I encountered problems with the latest release. I'm using Ubuntu 18.04 LTS (64-bits) and the problem is that it simply loads but the callback in bcrypt_hash doesn't get called at all, it works fine when I use wine and the .dll binary or downgrade to v2.2.2.

**Comment by czerwony03** [comment]
I had same problem on `Ubuntu 18.04.4 LTS`.
Solved it by reordering plugins in `server.cfg`.
My current plugin config:
`plugins samp-compat.so FCNPC.so crashdet.so bcrypt-samp.so sscanf.so streamer.so mysql_mariadb_static.so MapAndreas.so merrandom.so pawncmd.so praknet.so sampvoice.so`
